### ISSUE TITLE
Second-level modules not found unless their parent is a `mod.rs`

### ISSUE THREAD

**Issue by kpreid** [sourcefrog/cargo-mutants#102]
Given a project structure with `src/lib.rs`:

```rust
mod modules;
```

`src/modules.rs`:

```rust
mod foo;
```

and `src/modules/foo.rs` containing a function that could be mutated, `cargo mutants` does not mutate the function and instead produces a warning and finds no mutants:

```rust
   0.645927098s  WARN src/modules.rs:2: mod Ident { sym: foo, span: bytes(28..31) } not found
```

However, it succeeds if `src/modules.rs` is renamed to `src/modules/mod.rs`.

It seems that `cargo mutants` v1.2.0 is not correctly calculating module paths for children of modules whose source files are not named using the `mod.rs` style.

**Comment by sourcefrog** [comment]
Thanks for the report.
