### ISSUE TITLE
Alternating between mutants with and without '+nightly' does some odd things

### ISSUE THREAD

**Issue by cehteh** [sourcefrog/cargo-mutants#114]
I did some 'cargo mutants' runs on one of my projects alternating between '+nightly' and normal (stable) builds. Cargo mutants then reported problems in functions that should be disabled behind a 'feature' gate. The feature is selected by 'build.rs', so to by best guess so far there is something strange going on keeping state from previous builds that where using the other toolchain.
Running 'cargo clean' fixed these problems, that's why I conclude that its prolly some state left from the former build.

I haven't be able to isolate this in a simple test case. When you have any idea whats going on here it, maybe you can fix it already. If not I can try to make a testcase sometime next, just leave this ticket open and nag me about more infos.

**Comment by cehteh** [comment]
could this be because:

"""
cargo-mutants does not yet understand conditional compilation, such as #[cfg(target_os = "linux")]. It will report functions for other platforms as missed, when it should know to skip them.
"""

**Comment by sourcefrog** [comment]
That quote is correct: it doesn't currently understand cfg gates, so will
report code as untested that actually is not included in the build at all.

But, I don't know yet of any way that this would cause inconsistent results
over repeated builds on different toolchains, or that are affected by
`cargo clean`. Maybe your `build.rs` is not really hermetic or
deterministic, and won't generate the same results on consecutive builds.

Martin

**Comment by sourcefrog** [comment]
Aside from #50 I don't think this is actionable without a reproduction case, and I suspect it's due to your build script. Please reopen if you have more information.
