### ISSUE TITLE
gitignore recommendations?

### ISSUE THREAD

**Issue by wainwrightmark** [sourcefrog/cargo-mutants#126]
Hi
I love the tool but I've noticed it generates a lot of files and I can't find any guidance about what I should add to `.gitignore`

At the moment I'm adding `mutants.out` and `mutants.out.old` but I wonder whether I should actually be including some of these files e.g. `mutants.json`, `missed.txt` etc.

I know there may not be hard and fast rules about this but I think it would be good to have a page in the book explaining possible options. (Happy to write it an submit a PR if someone has a good answer to this question).

**Comment by sourcefrog** [comment]
All the generated files should be in `mutants.out`, which is then renamed to `mutants.out.old`, so `/mutants.out*` should be enough to ignore everything. If it's generating anything else please let me know. 

If you would like to send a PR adding something to the book that would be welcome.
