### ISSUE TITLE
Don't emit mutants that are the same as the source

### ISSUE THREAD

**Issue by xd009642** [sourcefrog/cargo-mutants#134]
This issue follows on from https://github.com/sourcefrog/cargo-mutants/issues/25 with the added suggestion of boolean/numeric literals (maybe &str but I imagine that's less necessary).

So in serde, you can't supply literals to the `default_value` attribute which leads to this pattern in peoples code:

```rust
fn true_value() -> bool {
	true
}

#[derive(Deserialize)]
pub struct Foo {
	#[serde(default="true_value")]
	bar: bool
}
```

Currently, cargo-mutants will replace `true` with `true`, given the prevalence of serde in the ecosystem I imagine these functions are present in a lot of projects - although I have no data to back that up beside anecdotal evidence.

**Comment by sourcefrog** [comment]
In this case one could mark `true_value` as skipped.

But yes, I agree it would be nice to skip functions where we can tell they
return the same value as the mutation.

Martin
