### ISSUE TITLE
Use of RUSTFLAGS="--error-format=json" causes cargo mutants to fail

### ISSUE THREAD

**Issue by TomMD** [sourcefrog/cargo-mutants#136]
```
$ RUSTFLAGS="--error-format=json" cargo mutants
...
error: Option 'error-format' given more than once
```

That error is repeated many times till termination with:

```
*** result: Failure

   1.281211253s ERROR cargo build failed in an unmutated tree, so no mutants were tested
```

**Comment by sourcefrog** [comment]
This seems to come from the fact that `cargo build` fails with that `RUSTFLAGS` set, regardless of anything in cargo-mutants:

```
; env RUSTFLAGS="--error-format=json" cargo build 
   Compiling unix_mode v0.1.4-pre (/home/mbp/src/unix_mode)
error: Option 'error-format' given more than once

error: could not compile `unix_mode` (lib)
```

I'm testing here on a very simple tree that has no `build.rs`, https://github.com/sourcefrog/unix_mode.

This looks a bit like https://github.com/rust-lang/cargo/issues/6375 or https://github.com/rust-lang/cargo/issues/11452 but I'm not sure it's exactly the same. It seems more like a cargo bug than a cargo-mutants bug.

It would be possible for cargo-mutants to parse `RUSTFLAGS` and strip out things that we might think won't work with `cargo build`, but I don't know if that really fits here. Maybe it's better to just not pass it.

I filed https://github.com/rust-lang/cargo/issues/12486 and unless some new information emerges I don't think there's anything to do in cargo-mutants.

**Comment by sourcefrog** [comment]
As @ehuss commented there https://github.com/rust-lang/cargo/issues/12486?notification_referrer_id=NT_kwDOAAVI87E3MzY1MTE5ODcxOjM0NjM1NQ#issuecomment-1675973644

> If you want JSON output, the correct way to do that is cargo --message-format=json.
