### ISSUE TITLE
Baseline always runs tests with --workspace, which may include unwanted tests

### ISSUE THREAD

**Issue by alexejrotar** [sourcefrog/cargo-mutants#151]
I am working in a workspace with multiple crates. Some have tests that depend on stuff like DBs. As pointed out in the documentation, I tried to exclude those crates from mutation testing, or similarly to explicitly run mutation testing in specific packages only. No matter how I do it, the baseline tests fail because apparently it always executes `cargo test --workspace` and runs all the tests, including those with external dependencies and they naturally fail. So I tried passing `--exclude <crate>`. That made the baseline tests pass but all the following tests failed because this option can only be used with the `--workspace` option. So I passed this one along but then the baseline tests fail again because I am not allowed to use `--workspace` twice and the baseline tests already have that.

Is there any way to do what I am asking? It seems to that what I want should be the default behavior: when excluding crates from mutation tests, their tests should not be run at all. And when running with the `-d` option, it should only run tests in that directory, not the entire workspace. In short, I think the `--workspace` option might not be the optimal way for running the baseline tests.

**Comment by sourcefrog** [comment]
Hi, thanks for reporting that. This is, as you identified, a bad consequence of the current approach of running all the tests in the workspace.

In the next release, probably within a month, I'm planning to change this to:
* Have an option to generate mutants only for selected packages, by default the cwd package
* For each mutant, by default, run only its own package's tests
* In the baseline run, similarly, run only the tests for the packages that will be tested

**Comment by alexejrotar** [comment]
Hi, thanks a lot for the quick reply! The change you suggest sounds good, exactly what I would expect. Look forward to it 😄

**Comment by sourcefrog** [comment]
@alexejrotar maybe you can try out https://github.com/sourcefrog/cargo-mutants/pull/154 and let me know if that works in your tree.

**Comment by alexejrotar** [comment]
It worked with the `-f` option, that's great! Two remarks though: It still runs all tests when using `-d` with some directory. Also, it seems to always copy everything, which in my case takes quite a while. I would expect it to behave like `cargo test`. When running it in a directory with a `Cargo.toml`, I assumed it to copy only the subtree along with (transitive) dependencies, run tests of this crate only, and mutate files in this crate only.

However, I can still use `-f`, so that's great already. If you don't agree with my other remarks, I'm fine with that. Thanks for the effort :)

**Comment by sourcefrog** [comment]
> It worked with the `-f` option, that's great!
Thanks for testing it!

> Two remarks though: It still runs all tests when using `-d` with some directory.

Yep, that is the expected current behavior, but I think it should change to be more like `cargo test`, as you say: #156.

> Also, it seems to always copy everything, which in my case takes quite a while. I would expect it to behave like `cargo test`. When running it in a directory with a `Cargo.toml`, I assumed it to copy only the subtree along with (transitive) dependencies, run tests of this crate only, and mutate files in this crate only.

Right, it does currently copy the whole tree as a simple way to get `path = "../other"` dependencies and so that every package can be mutated. You're right that we could narrow it to only the packages that will be mutated and their transitive dependencies.

I have also thought about adding an option to run the tests in place in the source tree, https://github.com/sourcefrog/cargo-mutants/issues/157.

Just wondering about your source tree: it tries to exclude `target/` directories. Is there so much Rust source and so on that the copy is inherently very slow, e.g. if you just `cp -r` a clean directory?

> 
> However, I can still use `-f`, so that's great already. If you don't agree with my other remarks, I'm fine with that. Thanks for the effort :)

**Comment by alexejrotar** [comment]
Yes, copying the tree would take as long, I guess. It's not only rust code in there. I guess, it is somewhat special, so maybe you shouldn't optimize for my setup. I suppose, for most user cases, copying the entire tree shouldn't be that bad.

**Comment by sourcefrog** [comment]
Would copying only the to-be-mutated packages help much?

I can imagine some trees would have very large checked-in testdata that could be slow to copy. For that, I guess the best option is to optionally test in-place.

I also thought about excluding files following `.gitignore` or `.ignore`.

**Comment by sourcefrog** [comment]
Released in https://github.com/sourcefrog/cargo-mutants/releases/tag/v23.10.0

**Comment by alexejrotar** [comment]
In my case, copying only affected files would help because there are some large files that are not used in tests and also there are non-rust packages (eg node), which explains why excluding target is not enough. But excluding files from `.gitignore` would probably have almost the same speed up and might be easier to implement. Thanks again for the quick fix!
