### ISSUE TITLE
Select packages to mutate the same way as `cargo test`

### ISSUE THREAD

**Issue by sourcefrog** [sourcefrog/cargo-mutants#156]
Currently, if you run `cargo mutants` in a directory inside a workspace, it generates mutants for every package in the workspace, subject to other filters.

Probably it should instead mutate only the package in the current (or `-d`) directory, with options to include others or to test the whole workspace.

Changing this now would unfortunately mean that anyone who has set up CI or other scripts with cargo-mutants might have to add `--workspace` to continue to test everything, but I think it's still worth it.

**Comment by kpreid** [comment]
I would suggest that it should [behave exactly the same as Cargo itself](https://doc.rust-lang.org/cargo/reference/workspaces.html#package-selection):

> If neither of those flags are specified, Cargo will use the package in the current working directory. If the current directory is a [virtual workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-workspace), it will apply to all members (as if `--workspace` were specified on the command-line).
>
> ...
> 
> The optional default-members key can be specified to set the members to operate on when in the workspace root and the package selection flags are not used:

**Comment by sourcefrog** [comment]
@kpreid you could try out https://github.com/sourcefrog/cargo-mutants/pull/161 if you like

**Comment by sourcefrog** [comment]
Fixed in 23.11.0!
