### ISSUE TITLE
Only invoke cargo metadata for desired targets

### ISSUE THREAD

**Issue by mschlaipfer** [sourcefrog/cargo-mutants#164]
Copying from a similar issue: https://github.com/bbqsrc/cargo-ndk/issues/83

Unlike most other cargo tools, `cargo metadata` counter-intuitively defaults to including all targets. This means that with the current logic, `cargo-mutants` ends up processing (and thus downloading dependencies for) all targets even though the user has specifically called out the targets they want to build for. Specifically, in the `MetadataCommand` invocation here
https://github.com/sourcefrog/cargo-mutants/blob/8898c073a46cd1f3c853e6bf7c1edc9310c4f779/src/workspace.rs#L115

`cargo-mutants` should probably always specify [`--filter-platform`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#output-options) to each of the specified targets via [`MetadataCommand::other_options`](https://docs.rs/cargo_metadata/0.15.2/cargo_metadata/struct.MetadataCommand.html#method.other_options). Unfortunately `--filter-platform` only takes a single target triple, so you'd have to run metadata once per platform, but that's probably what you'd want to do anyway, since the dependency closure can vary between platforms.

Alternatively, if you aren't using any of the dependency metadata info, and are just invoking `cargo metadata` in order to get information about the workspace, you can call [`MetadataCommand::no_deps`](https://docs.rs/cargo_metadata/0.15.2/cargo_metadata/struct.MetadataCommand.html#method.no_deps), which also makes the `cargo metadata` invocation a fair bit faster!

**Comment by sourcefrog** [comment]
Great idea, thanks @mschlaipfer and @jonhoo!

I had noticed that sometimes there was a perceptible pause while cargo updated dependencies, and it doesn't need that information at all. Sounds like `no_deps` will work.
