### ISSUE TITLE
Show number of mutants processed

### ISSUE THREAD

**Issue by xd009642** [sourcefrog/cargo-mutants#21]
So I've been running mutants on my code base all day, and while showing only the failing mutants and current one does keep the output nice and terse it does mean I have no idea how many more are left to run before it's finished. Something like `N/total` on the in-progress line would helpful for gauging if it's worth waiting for it to finish or whether I should consider killing it and adding some ignores in the codebase :sweat_smile:

**Comment by sourcefrog** [comment]
👍🏻 though as a workaround you can look at the number of files in `mutants.out/log/` which will have one per build.

**Comment by sourcefrog** [comment]
![image](https://user-images.githubusercontent.com/346355/153783977-6c32dd26-f08f-4c1a-9147-309d900ab714.png)
