### ISSUE TITLE
Build with `cargo test --no-run` or `nextest test run --no-run`

### ISSUE THREAD

**Issue by sourcefrog** [sourcefrog/cargo-mutants#237]
As suggested by `sunshowers` in https://github.com/sourcefrog/cargo-mutants/issues/85#issuecomment-1879146942, it would be better to build with these commands rather than `cargo build --tests`, as it uses a different profile and might have other differences in some crates.

**Comment by ASuciuX** [comment]
Hey, @sourcefrog ! Hope you're doing great! 

What is the current status for `cargo nextest` integrated? We would like to use it, and there is the flow for complete sync which, given the difference in results we shared https://github.com/sourcefrog/cargo-mutants/pull/223#issuecomment-1883997255, is not even worth running without it.

**Comment by sourcefrog** [comment]
Hi @ASuciuX, this shipped in [24.1.0](https://github.com/sourcefrog/cargo-mutants/blob/main/NEWS.md#2410) a couple weeks ago and you should be able to use it now by just installing through `cargo binstall` or `install-action` and then passing `--test-tool=nextest`.  

I'm keen to hear how it turned out on your tree; please start [discussion](https://github.com/sourcefrog/cargo-mutants/discussions/categories/q-a) with any results or issues?

**Comment by sourcefrog** [comment]
This particular issue (237) is for a small follow-on work to get better separation between builds and tests. Fixing this will give more precise measurements of build vs test time, and better distinguish between caught and unviable mutants. But, as far as I know, nextest is perfectly usable without it. 

There's also #238 as a follow on which is also just about better reporting and should not be a blocker.

**Comment by ASuciuX** [comment]
Got it, thanks. I'll start one after we use it more, probably in the following days.
