### ISSUE TITLE
Avoiding applying mutants which are equivalent to the source

### ISSUE THREAD

**Issue by xd009642** [sourcefrog/cargo-mutants#25]
So a pattern I've seen a number of places in rust code (and have in my own code in places) is:

```rust
impl SomeStruct {
	pub fn new() -> Self {
	    Self::default()
    }
}
```

In cargo-mutants it will take this function and apply the `Default` mutagen to it creating code that is equivalent to the source code and then register as not caught. This could be solved by `#[mutants::skip]` so it's not a _must have_ but I figured it might be a reasonably simple/nice optimisation for working out the number of mutants. Similarly if someone has a function which returns a bool but is just a single literal the only valid mutagen is the negation of that constant not the constant itself

**Comment by sourcefrog** [comment]
I can't think of any strongly general way to do this without deeply understanding the Rust semantics, maybe by reading MIR. (Which might be cool; maybe later.)

But we could at least handle some common cases of `new <-> default`, functions that are empty, functions that return a literal constant, etc.

**Comment by xd009642** [comment]
Maybe using syn and seeing if the function has one expression which is an explicit return where the text is `<T>default();` where T is `Default`, `Self` or `$StructName` and it either impls or derives default in the same file.

Default is the hardest case, using syn to find bool literals like that has less edge cases

**Comment by sourcefrog** [comment]
Some specific cases we could probably skip

- [ ] `new() -> Self` -- possibly we could look inside but it seems unlikely we can think of a better valid mutation
- [ ] `Default::default`
- [ ] functions that return `()` and already have an empty body
- [ ] functions whose body is the same as the mutation at the AST level (which would cover some of the above points)

**Comment by sourcefrog** [comment]
I think I've fixed the major cases of pointless mutations:
 * `new`
 * `Default::default`
 * empty functions `-> ()` 

We could go further and look for cases where the function body is exactly the same as the generated mutation, but that seems perhaps unlikely. 

I'll close this bug and we can open more if any other cases of clearly-pointless mutations can be identified.
