### ISSUE TITLE
Concern: Resource Accumulation from Individual Mutant Processes

### ISSUE THREAD

**Issue by ASuciuX** [sourcefrog/cargo-mutants#265]
Hey @sourcefrog,

Are individual mutant processes terminated upon completion, or is the termination process only initiated after the entire `cargo mutants` run is finished? We are dealing with a substantial number of mutants, approximately 7.5k, and I've observed numerous processes that have minimal resource consumption. If these processes persist beyond their respective mutant runs, the accumulation of these smaller processes could potentially exhaust machine resources, blocking the completion of all mutants due to resource constraints.

If the resources are freed, this issue can be closed. If that's the case, I am very curious about what all these processes are. 

 
![image](https://github.com/sourcefrog/cargo-mutants/assets/151519329/99f82e08-9eb7-48ef-a61a-d37d769b064c)

<img width="1539" src="https://github.com/sourcefrog/cargo-mutants/assets/151519329/0c6a1a12-dfde-44fc-a733-31a006e7b974">

**Comment by sourcefrog** [comment]
Those look like threads inside the mutants process. Is the number growing over time? It looks like your overall ram usage is quite low.

**Comment by sourcefrog** [comment]
This would be easier to interpret/explain if you show them in a tree with `pstree` or turning on the tree option in htop.

However, what you seem to be showing here is just that there are 80 odd threads. Threads don't cost much in themselves.

You are running cargo-mutants with `-j3 --test-tool=nextest`. cargo-mutants has 3 threads, one for each job, as expected. Each nextest process apparently launches 25 internal threads. cargo-mutants launches one nextest process for each mutant and waits for it to complete (or timeout). All the nextest threads must necessarily exit when the nextest process exits or is killed. 

You seem to have a lot of memory free.

Unless you're seeing the total number of processes or memory consumption on the system grow without bound as the mutants process runs then I don't think there's a problem here. 

----

Incidentally and unrelated to the threads, if `/tmp` is not a ramdisk on your machine then I would recommend mounting one and using it as the TMPDIR for cargo-mutants (specifically for mutants, not system wide), as you have a good amount of memory. Rust builds and tests write a *lot* of files and tmpfs is faster than ext4. See https://mutants.rs/performance.html#ramdisks

**Comment by sourcefrog** [comment]
I think that answers it so I'll close.

Questions are welcome but to keep things tidy please file them under [Q&A](https://github.com/sourcefrog/cargo-mutants/discussions/categories/q-a) unless it's clear that it's a bug.
