### ISSUE TITLE
yaml validate example github setups?

### ISSUE THREAD

**Issue by sourcefrog** [sourcefrog/cargo-mutants#266]
The book includes example YAML config for GitHub actions. 

We could potentially 
1. Move it to a separate YAML file that's included into the book. This would incidentally make it easier for people to copy and use.
2. Then run a YAML schema validator to make sure there are no typos.
----

There is <https://github.com/nektos/act> to actually run them locally, but that would take a while, and requires having Docker etc. 

There's also <https://github.com/mpalmer/action-validator> which seems just right.

**Comment by kevinmatthes** [comment]
There is also another Action:  https://github.com/devops-actions/actionlint.

It is a wrapper around the GHA validator used by GitHub's official Super Linter.

**Comment by sourcefrog** [comment]
hm, thanks!

**Comment by sourcefrog** [comment]
It looks like action-validator is nice to run locally (but has some gaps like https://github.com/mpalmer/action-validator/issues/70) but maybe actionlint is a good fit for CI.
