### ISSUE TITLE
Mutations applied to file with inner `#![cfg(test)]` attribute

### ISSUE THREAD

**Issue by john-h-kastner-aws** [sourcefrog/cargo-mutants#286]
For a crate containing two files `lib.rs` and `test.rs`

`lib.rs`:
```rust
mod test;
```

`test.rs`:
```rust
#![cfg(test)]

fn foo() -> bool { false }
```

I expect that `cargo mutants --list` will not list any mutations, but I see

```console
jkastner@dev % cargo mutants --list
src/test.rs:3:20: replace foo -> bool with true
```

I suspect this is because `cargo mutants` is not checking for inner attributes on files. Moving `#![cfg(test)]` to an outer attribute on the `mod test;` statement lets things work as expected. Inner attribute are also detected properly if I move the definition of the `test` module inside `lib.rs`.

**Comment by sourcefrog** [comment]
Thanks, I can imagine how we might not be checking for that and I agree it's a bug.
