### ISSUE TITLE
File name too long on ecryptfs

### ISSUE THREAD

**Issue by lukaszwojtow** [sourcefrog/cargo-mutants#31]
It seems like ecryptfs has a limit of 143 chars for file name. That causes cargo mutants to fail sometimes.
Would you accept a PR with some limit imposed here https://github.com/sourcefrog/cargo-mutants/blob/26199b362a444ed225dd6a7322851252feabea8a/src/log_file.rs#L36 ?

**Comment by sourcefrog** [comment]
Sure, thanks!

**Comment by sourcefrog** [comment]
We will have to be careful of cases where this could cause file names to collide between different mutants, but that should not be too hard.

**Comment by sourcefrog** [comment]
Thanks for filing. Looking at this some more, I decided rather than truncating the filename, it's better to just include only the file name and line number to start with.

848e0759f3944d55bb1be5387bbeb7b1d6541d98 should fix this; let me know?
