### ISSUE TITLE
`.ignore` files can exclude files that should be copied

### ISSUE THREAD

**Issue by TheLostLambda** [sourcefrog/cargo-mutants#321]
Firstly this is an incredibly cool tool, and after taking my crates out of the workspace, I got it working and found some cases I'd missed!

But when it comes to the issue at hand, if you try cloning this repository: https://github.com/TheLostLambda/pg-pipeline

Then running `cargo mutants --workspace`, it seems that all of the insta snapshots are reported as new, and the unmutated version fails to build! I fixed this problem by copying the `polychem` crate to a new directory (this is where most of the code is so far), updating the `Cargo.toml` to remove the workspace lint inheritance, then pointing it to a `nom-miette` that had also been taken out of the workspace, and that works fine!

Let me know if you're seeing the same issue I am, and if I can help by providing any more information!

**Comment by sourcefrog** [comment]
Hi, thanks! 

Could you please try with the current git head of Mutants and see if that fixes it?

**Comment by sourcefrog** [comment]
It seems like the problem might be connected to copying the tree. Perhaps copying the tree is confused by something about the workspace. 

With `cargo mutants --package polychem  --no-shuffle --in-place` seems to work.

Without `--in-place` it fails the baseline tests.

With `--in-place` then testing the whole workspace seems to work as well: `cargo mutants --workspace --in-place`...

----

OK, this is the problem: your `/.ignore` includes `*.snap`. By default when copying the tree cargo-mutants respects .ignore and .gitignore files, and so the snapshots are not copied.

You can turn this off with `--gitignore false` (or a config setting) and then it seems to work.

Perhaps I should change the default to not follow gitignore, or to exclude `target/` but nothing else. That would make it more likely to work out of the box but slightly slower and maybe using more scratch space.

But, to help me work out if this is likely to be a good default, can you say why you added that config?

**Comment by TheLostLambda** [comment]
@sourcefrog A good find!

Yeah, the `.ignore` file isn't something git seems to pick up on or care about (at least on my version of git), so all of those snapshots are still certainly checked into version control, but including that in a `.ignore` file was done to exclude those files from my text-editor's (https://helix-editor.com/) fuzzy-finder! Without that line, if I go to find some file, I have to sift through the hundred-plus snapshots too!

It also helps other tools (like ripgrep) pass them over as well.

Perhaps a fix could be that cargo-mutants only pays attention to specifically `.gitignore` files? That way you copy all of the same files that would normally be committed (which should work, especially if you're testing in CI)!

Let me know what you think about that solution, and good quick find!

**Comment by sourcefrog** [comment]
Yep, reading from only `.gitignore` and not `.ignore` sounds good to me.

(In fact I should add `*.snap` to `.ignore` for the same reason!)

**Comment by sourcefrog** [comment]
I also started documenting the process I used to diagnose this in https://github.com/sourcefrog/cargo-mutants/wiki/Troubleshooting

**Comment by TheLostLambda** [comment]
I like a good first issue, and you've already been kind enough to do the hard work here — I'll whip up a PR!
