### ISSUE TITLE
Document `--timeout-multiplier`

### ISSUE THREAD

**Issue by sourcefrog** [sourcefrog/cargo-mutants#323]
https://github.com/sourcefrog/cargo-mutants/blob/843b78a9daa367287655c69bf45ba619c8bdbd2c/src/main.rs#L289-L291

It looks like I forgot to add this into the book; it should be mentioned in places that discuss timeouts

- [ ] https://mutants.rs/timeouts.html

**Comment by zaneduffield** [comment]
@sourcefrog I think this can be closed now.

**Comment by sourcefrog** [comment]
Thanks!
