### ISSUE TITLE
cfg attribute when running `cargo-mutants`?

### ISSUE THREAD

**Issue by TimDiekmann** [sourcefrog/cargo-mutants#34]
This is a really nice crate and works pretty great!

I have one issue: I really don't want `mutants` to be a non-dev dependency.  Do you think it's possible to define an attribute which can be checked, so for example the following example would work? This probably won't need the `mutants` crate at all.
```rust
#[cfg_attr(mutants, mutants::skip)]
fn function_to_skip(&mut self);
```

Another possibility would be to set the `test`-attribute when creating mutations, so this would work (this would only need a `dev-dependency`):
```rust
#[cfg_attr(test, mutants::skip)]
fn function_to_skip(&mut self);
```

**Comment by sourcefrog** [comment]
Thanks!

I think something like this is possible.

Due to the way cargo-mutants works, we currently look for the marker attributes by looking at the AST rather than running the real compiler's attribute/cfg evaluation system. (It would be more flexible to do that but I don't currently see a way to do it.) I could teach cargo-mutants to recognize either of those patterns.

In the first case it's kind of "grabbing" the feature flag "mutants" in this crate's namespace but perhaps that's OK...

**Comment by TimDiekmann** [comment]
Great to hear!

If you only parsing the AST it's most probably better to prefer the `test`-attribute pattern as (for me) it feels intuitive (as in: "I want to skip mutation this function when testing this create").

Is it possible to provide some help on implementing this without knowing exactly how this crate is working?

**Comment by TimDiekmann** [comment]
I played around a little bit and this seems to work (enhancing `attr_is_mutants_skip`): 
```rust
/// True if the attribute is `#[mutants::skip]`.
fn attr_is_mutants_skip(attr: &Attribute) -> bool {
    if attr.path
        .segments
        .iter()
        .map(|ps| &ps.ident)
        .eq(["mutants", "skip"].iter()) {
        return true
    }

    if !attr.path.is_ident("cfg_attr") {
        return false;
    }

    if let syn::Meta::List(meta_list) = attr.parse_meta().unwrap() {
        let mut nested_metas = meta_list.nested.iter().filter_map(|meta| {
            if let syn::NestedMeta::Meta(syn::Meta::Path(path)) = meta {
                Some(path.segments.iter().map(|ps| &ps.ident).take(2).collect::<Vec<_>>())
            } else {
                None
            }
        }).take(2).collect::<Vec<_>>();
        if (nested_metas[0] == ["test"] || nested_metas[0] == ["mutants"]) && nested_metas[1] == ["mutants", "skip"] {
            return true;
        }
    }

    false
}
```
