### ISSUE TITLE
Allow copying `.git` 

### ISSUE THREAD

**Issue by xd009642** [sourcefrog/cargo-mutants#348]
So I'm in a _definitely very unique_ situation where I have a test that requires the repos `.git` folder so I need something a bit more aggressive than the `--gitignore true` flag. I'm currently using `--in-place` in a separate clone of the project to avoid accidentally breaking something so there is an easy way round this if this is too exotic

For the interested this is because I interact with the coveralls API and part of that API you provide some git and github metadata so I test against the repos own metadata to make sure I'm filling out the API fields correctly

**Comment by xd009642** [comment]
Actually, despite working around that cargo-mutants doesn't run on [tarpaulin](https://github.com/xd009642/tarpaulin)... Dose cargo-mutants make use of unix signals if so that might break things for me :thinking:

**Comment by sourcefrog** [comment]
The easiest workaround for the git issue is probably `--in-place`, or
copying it yourself then using that.

The main thing cargo-mutants uses signals for is to kill hung tests, and to
stop them if it's interrupted itself.

Can you describe how to reproduce the problem with Tarpaulin?

**Comment by xd009642** [comment]
So tarpaulin tests instrument binaries with breakpoints and do coverage which involves intercepting signals going to the process and handling them in code. There's a possibility I'm intercepting the cargo mutants kill signal and then failing the test because it's got an unexpected termination signal :thinking: 

Reproducing is pretty simple, it's just cloning tarpaulin and running cargo mutants on it 

```
git clone --depth 1 https://github.com/xd009642/tarpaulin
cd tarpaulin
cargo mutants --in-place 
```
