### ISSUE TITLE
Exclude specified paths from mutants generation

### ISSUE THREAD

**Issue by dmoka** [sourcefrog/cargo-mutants#58]
I believe that it would be handy to exclude specified paths from the mutants generation.

Let's say that I want to exclude things like configuration logic or some test helper logic files, located within the `src` directory. Right now the default behaviour of `cargo mutants` command is that it tries to generate mutants for every file in the `src`  directory and in their child directories.

I could envision having a command line parameter as follows:

```
cargo mutants --exclude <regexes-for-paths-to-be-excluded>
```

### Prerequisite:
Git clone [test repo](https://github.com/dmoka/test-repo-for-cargo-mutants.git)

### Steps:
1. Go to the main directory of the cloned repo
2. Execute the following command
```
cargo mutants --exclude "(\/src\/tests)" "(\/src\/config)"
```

### Expected behaviour:
Every file which is located in either `/src/tests` or `/src/config` directories are excluded from mutants generation.

### Actual behaviour:
Because of the default behaviour of `cargo-mutants` (and due to the non-existency of this command line parameter) there are mutants generated for the files both in `/src/tests` and `/src/config`

**Comment by sourcefrog** [comment]
Yep. There is already `-f` to say which files you _do_ want to test. We could usefully and easily add the opposite. I think it should be a glob (as `-f` is) not a regexp.

**Comment by dmoka** [comment]
You are right, glob is indeed a much better one for paths.

I believe that it would be a nice `first-issue` for me, would be glad to pick this task up. Is it fine by you?

**Comment by sourcefrog** [comment]
That would be great, thanks! You should be able to work off the existing `-f` implementation.

**Comment by dmoka** [comment]
[PR](https://github.com/sourcefrog/cargo-mutants/pull/65) has been created, ready to be reviewed
