### ISSUE TITLE
Check `cargo fmt` from CI

### ISSUE THREAD

**Issue by sourcefrog** [sourcefrog/cargo-mutants#67]
Block merging changes that don't have canonical formatting.

**Comment by dmoka** [comment]
Additionally, we could also execute clippy in CI, resulting in a more ergonomic and standardized code. And in some places, if it is needed and reasonable, we could ignore specific warnings.

**Comment by sourcefrog** [comment]
Yep, we do already check Clippy:

https://github.com/sourcefrog/cargo-mutants/blob/93a26a0d5468b552f6a58a12e2a98ca6881dff1f/.github/workflows/tests.yml#L39-L40
