### ISSUE TITLE
Is it possible to pass in a list of files to mutate?

### ISSUE THREAD

**Issue by srazzell** [sourcefrog/cargo-mutants#97]
I see there's a --file argument. Does that only take a single file or a glob? I'm wondering if it's possible to provide a list of files to mutate. I'm trying to run this tool on a pull request and limit the mutations to only the files that were changed. Thanks.

**Comment by sourcefrog** [comment]
It takes a glob. If there's a slash it's relative to the root; if there's no slash it matches a file in any directory. You can repeat the option, too.

A PR might conceivably introduce a bug in file A that only shows up when you mutate a function in file B, not A, but it's probably less likely.

It would be nice to add docs on this when you get it working!

**Comment by srazzell** [comment]
Ah, perfect. Repeating the option worked for me. I didn't see anything that mentioned you could do that.

**Comment by sourcefrog** [comment]
I'll leave this reopen to improve the docs

**Comment by sourcefrog** [comment]
@srazzell take a look at https://github.com/sourcefrog/cargo-mutants/commit/fbfde3d7cab35f49a3ed0f4d53a68a5695a32363 and please let me know or suggest a change for anything that is unclear
